### ISSUE TITLE
答案之书回答乱码

### ISSUE THREAD

**Issue by alsojiangshi** [GeneralK1ng/Kookies#6]
如题
![屏幕截图 2024-10-05 132021](https://github.com/user-attachments/assets/88fc3809-7a50-4056-b79b-1152dc762531)

**Comment by GeneralK1ng** [comment]
服务端有采用utf8启动吗

**Comment by alsojiangshi** [comment]
> 服务端有采用utf8启动吗

没，应该是Unicode，不知道哪里改

**Comment by alsojiangshi** [comment]
解决了
