### ISSUE TITLE
修改AutoConfig.yml文件无法修改配置

### ISSUE THREAD

**Issue by alsojiangshi** [GeneralK1ng/Kookies#7]
如题，欲通过修改mcl\config\org.laolittle.plugin.AutoGroup\AutoConfig.yml来修改如戳一戳的时间间隔等配置，但不生效且重启mirai后.yml恢复原样
![image](https://github.com/user-attachments/assets/be83b3d7-7eb1-44f1-a7db-42aa771b9cf3)

**Comment by GeneralK1ng** [comment]
这貌似不是kookie的config...

**Comment by alsojiangshi** [comment]
啊啦啦交错地方了x_x
